--
--INSERT INTO GROUPS(id, name, c_vall) values (1, 'name', 1);
--INSERT INTO GROUPS(id, name, c_vall) values (2, 'name2', 2);
--UPDATE GROUPS SET name = 'name3' WHERE id = 2;
--DELETE FROM GROUPS WHERE id = 1;
--
--ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';
--
--BEGIN
--    get_html(TO_TIMESTAMP('2022-05-12 23:52:26.355000', 'YYYY-MM-DD HH24:MI:SS.FF'));
--END;
--
--delete
--from STUDENTS_LOGS;
--delete
--from students
--where name = 'John';
--
--INSERT INTO STUDENTS(id, name, group_id)
--values (5, 'John', 1);
--
--delete
--from STUDENTS;
--
--
--delete
--from students;
--
--BEGIN
--    lab5_package.recovery(TO_TIMESTAMP('2022-05-12 23:52:26.355000', 'YYYY-MM-DD HH24:MI:SS.FF'));
--END;
--
--BEGIN
--    lab5_package.recovery(600);
--END;


